sudo: false

language: go
go:
  - 1.3.1

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/tools/godep
  - godep restore

script:
  - make test
