name: Release

on: [push]
# on:
#   push:
#     tags:     # Sequence of patterns matched against refs/tags
#       - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: |
          make archive GOOS=linux GOARCH=amd64
          make archive GOOS=freebsd GOARCH=amd64
          make archive GOOS=darwin GOARCH=amd64
      - name: Setup variables
        id: vars
        run: echo "::set-output name=githash::$(git rev-parse --short HEAD)"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload artifact
        id: upload-artifact-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/linux_amd64/forego-${{ steps.vars.outputs.githash }}-linux-amd64.tgz
          asset_name: forego-${{ steps.vars.outputs.githash }}-linux-amd64.tgz
          asset_content_type: application/x-tgz
      - name: Upload artifact
        id: upload-artifact-freebsd-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/freebsd_amd64/forego-${{ steps.vars.outputs.githash }}-freebsd-amd64.tgz
          asset_name: forego-${{ steps.vars.outputs.githash }}-freebsd-amd64.tgz
          asset_content_type: application/x-tgz
      - name: Upload artifact
        id: upload-artifact-darwin-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/darwin_amd64/forego-${{ steps.vars.outputs.githash }}-darwin-amd64.tgz
          asset_name: forego-${{ steps.vars.outputs.githash }}-darwin-amd64.tgz
          asset_content_type: application/x-tgz
